/* AUTO-GENERATED by protocol_sdk/tools/generate_errors_sdk.py */
/* DO NOT EDIT — run `make gen-sdk` to regenerate. */
#ifndef FERQON_ERRORS_H
#define FERQON_ERRORS_H

#include <stdint.h>

/* Numeric error code defines */
#define FERQON_E0001 1u  /* An unexpected error occurred */
#define FERQON_E0002 2u  /* Resource not found */
#define FERQON_E0003 3u  /* Request validation failed */
#define FERQON_E0004 4u  /* Rate limit exceeded */
#define FERQON_E0500 500u  /* Internal server error */
#define FERQON_E0010 10u  /* Firmware flashing failed */
#define FERQON_E0011 11u  /* Flash cooldown active */
#define FERQON_E0012 12u  /* Firmware unchanged — flash skipped */
#define FERQON_E0013 13u  /* Device is locked by another operation */
#define FERQON_E0020 20u  /* Device is busy */
#define FERQON_E0021 21u  /* Session not found or expired */
#define FERQON_E0022 22u  /* Device wait queue is full */
#define FERQON_E0030 30u  /* Authentication required */
#define FERQON_E0031 31u  /* Permission denied */
#define FERQON_E0040 40u  /* Device is offline */
#define FERQON_E0041 41u  /* Device not found */
#define FERQON_E0042 42u  /* Device does not support this capability */
#define FERQON_E0043 43u  /* Device communication error */
#define FERQON_E0050 50u  /* HIL test execution failed */
#define FERQON_E0051 51u  /* HIL test timed out */
#define FERQON_E0052 52u  /* HIL test run not found */
#define FERQON_E0053 53u  /* HIL assertion failed */
#define FERQON_E0060 60u  /* Configuration is invalid */
#define FERQON_E0070 70u  /* IoT operation failed */
#define FERQON_E0071 71u  /* IoT device not registered */
#define FERQON_E0072 72u  /* MQTT broker unavailable */
#define FERQON_E0080 80u  /* Serial port unavailable */
#define FERQON_E0081 81u  /* Serial communication error */
#define FERQON_E0090 90u  /* License validation failed */
#define FERQON_E0091 91u  /* Feature not available on current license tier */
#define FERQON_E0100 100u  /* Webhook test request failed */
#define FERQON_E0200 200u  /* OTA operation blocked by precondition failures */
#define FERQON_E0201 201u  /* Firmware version rollback not permitted */
#define FERQON_E0202 202u  /* Device did not respond to discovery request */
#define FERQON_E0310 310u  /* GitHub OAuth token exchange failed */
#define FERQON_E0311 311u  /* Operation not available for device tokens */
#define FERQON_E0312 312u  /* GitHub device flow authentication error */
#define FERQON_E0313 313u  /* Resource already exists or is in conflicting state */
#define FERQON_E0314 314u  /* Cannot leave team: you are the only leader */
#define FERQON_E0315 315u  /* Security key already exists */
#define FERQON_E0350 350u  /* CA certificate not found */
#define FERQON_E0351 351u  /* IoT configuration update failed */
#define FERQON_E0352 352u  /* Failed to start IoT simulator */
#define FERQON_E0353 353u  /* IoT simulator instance not found */
#define FERQON_E0354 354u  /* No previous firmware version available */
#define FERQON_E0355 355u  /* Device is not assigned to this team */
#define FERQON_E0356 356u  /* A transfer request is already pending for this resource */
#define FERQON_E0357 357u  /* Transfer request is not in the expected state */
#define FERQON_E0358 358u  /* Device ownership changed while transfer was in progress */
#define FERQON_E0359 359u  /* Signed firmware policy is enforced on this device */
#define FERQON_E0061 61u  /* Required configuration is missing */
#define FERQON_E0062 62u  /* Security configuration is unavailable */
#define FERQON_E0063 63u  /* The system is running with limited functionality */
#define FERQON_E0064 64u  /* The routing configuration could not be loaded */
#define FERQON_E0065 65u  /* The CORS policy configuration could not be loaded */

/* Error metadata table entry */
typedef struct {
    uint16_t    code;
    const char *tag;     /* "Ferqon.Exxxx" */
    const char *message;
    const char *category;
    uint8_t     retryable;
} ferqon_error_entry_t;

#define FERQON_ERROR_TABLE_SIZE 55u

#ifdef FERQON_ERRORS_IMPL
const ferqon_error_entry_t FERQON_ERRORS[FERQON_ERROR_TABLE_SIZE] = {
    { 1u, "Ferqon.E0001", "An unexpected error occurred", "internal", 0 },
    { 2u, "Ferqon.E0002", "Resource not found", "not_found", 0 },
    { 3u, "Ferqon.E0003", "Request validation failed", "validation", 0 },
    { 4u, "Ferqon.E0004", "Rate limit exceeded", "rate_limit", 1 },
    { 500u, "Ferqon.E0500", "Internal server error", "internal", 0 },
    { 10u, "Ferqon.E0010", "Firmware flashing failed", "hardware", 1 },
    { 11u, "Ferqon.E0011", "Flash cooldown active", "rate_limit", 1 },
    { 12u, "Ferqon.E0012", "Firmware unchanged — flash skipped", "capability", 0 },
    { 13u, "Ferqon.E0013", "Device is locked by another operation", "conflict", 1 },
    { 20u, "Ferqon.E0020", "Device is busy", "conflict", 1 },
    { 21u, "Ferqon.E0021", "Session not found or expired", "not_found", 0 },
    { 22u, "Ferqon.E0022", "Device wait queue is full", "rate_limit", 1 },
    { 30u, "Ferqon.E0030", "Authentication required", "auth", 0 },
    { 31u, "Ferqon.E0031", "Permission denied", "permission", 0 },
    { 40u, "Ferqon.E0040", "Device is offline", "device", 1 },
    { 41u, "Ferqon.E0041", "Device not found", "not_found", 0 },
    { 42u, "Ferqon.E0042", "Device does not support this capability", "capability", 0 },
    { 43u, "Ferqon.E0043", "Device communication error", "hardware", 1 },
    { 50u, "Ferqon.E0050", "HIL test execution failed", "hardware", 0 },
    { 51u, "Ferqon.E0051", "HIL test timed out", "hardware", 1 },
    { 52u, "Ferqon.E0052", "HIL test run not found", "not_found", 0 },
    { 53u, "Ferqon.E0053", "HIL assertion failed", "hardware", 0 },
    { 60u, "Ferqon.E0060", "Configuration is invalid", "config", 0 },
    { 70u, "Ferqon.E0070", "IoT operation failed", "network", 1 },
    { 71u, "Ferqon.E0071", "IoT device not registered", "not_found", 0 },
    { 72u, "Ferqon.E0072", "MQTT broker unavailable", "network", 1 },
    { 80u, "Ferqon.E0080", "Serial port unavailable", "hardware", 1 },
    { 81u, "Ferqon.E0081", "Serial communication error", "hardware", 1 },
    { 90u, "Ferqon.E0090", "License validation failed", "permission", 0 },
    { 91u, "Ferqon.E0091", "Feature not available on current license tier", "capability", 0 },
    { 100u, "Ferqon.E0100", "Webhook test request failed", "network", 1 },
    { 200u, "Ferqon.E0200", "OTA operation blocked by precondition failures", "conflict", 1 },
    { 201u, "Ferqon.E0201", "Firmware version rollback not permitted", "firmware", 0 },
    { 202u, "Ferqon.E0202", "Device did not respond to discovery request", "device", 1 },
    { 310u, "Ferqon.E0310", "GitHub OAuth token exchange failed", "auth", 1 },
    { 311u, "Ferqon.E0311", "Operation not available for device tokens", "auth", 0 },
    { 312u, "Ferqon.E0312", "GitHub device flow authentication error", "auth", 1 },
    { 313u, "Ferqon.E0313", "Resource already exists or is in conflicting state", "conflict", 0 },
    { 314u, "Ferqon.E0314", "Cannot leave team: you are the only leader", "conflict", 0 },
    { 315u, "Ferqon.E0315", "Security key already exists", "conflict", 0 },
    { 350u, "Ferqon.E0350", "CA certificate not found", "not_found", 0 },
    { 351u, "Ferqon.E0351", "IoT configuration update failed", "config", 0 },
    { 352u, "Ferqon.E0352", "Failed to start IoT simulator", "network", 1 },
    { 353u, "Ferqon.E0353", "IoT simulator instance not found", "not_found", 0 },
    { 354u, "Ferqon.E0354", "No previous firmware version available", "not_found", 0 },
    { 355u, "Ferqon.E0355", "Device is not assigned to this team", "conflict", 0 },
    { 356u, "Ferqon.E0356", "A transfer request is already pending for this resource", "conflict", 0 },
    { 357u, "Ferqon.E0357", "Transfer request is not in the expected state", "conflict", 0 },
    { 358u, "Ferqon.E0358", "Device ownership changed while transfer was in progress", "conflict", 0 },
    { 359u, "Ferqon.E0359", "Signed firmware policy is enforced on this device", "firmware", 0 },
    { 61u, "Ferqon.E0061", "Required configuration is missing", "config", 0 },
    { 62u, "Ferqon.E0062", "Security configuration is unavailable", "config", 0 },
    { 63u, "Ferqon.E0063", "The system is running with limited functionality", "config", 0 },
    { 64u, "Ferqon.E0064", "The routing configuration could not be loaded", "config", 0 },
    { 65u, "Ferqon.E0065", "The CORS policy configuration could not be loaded", "config", 0 },
};
#else
extern const ferqon_error_entry_t FERQON_ERRORS[FERQON_ERROR_TABLE_SIZE];
#endif /* FERQON_ERRORS_IMPL */

#endif /* FERQON_ERRORS_H */
