#!/usr/bin/env python3
"""
gen_platform_caps.py
--------------------
Generates platform capability headers and device channel definitions
from board capability YAML files.

Usage:
    python3 tools/gen_platform_caps.py <board.yml> [output_dir]
    python3 tools/gen_platform_caps.py --all
    python3 tools/gen_platform_caps.py --check

Generates:
    <output_dir>/platform_caps.h     - Platform constants and validation functions
    <output_dir>/pin_macros.h        - Inline capability check macros
    <output_dir>/device_channels.c   - Device descriptor channel array
    <output_dir>/board.json          - JSON mirror for backend tooling
    <output_dir>/capabilities.json   - Unified capabilities for driver matching
"""

import yaml
import json
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Any
from jsonschema import validate, ValidationError


def load_board_schema() -> Dict[str, Any]:
    """Load the board schema for validation."""
    schema_path = Path(__file__).parent / "schemas" / "board.schema.json"
    with open(schema_path) as f:
        return json.load(f)


def load_board_yaml(path: Path, schema: Dict[str, Any] = None) -> Dict[str, Any]:
    """Load and validate board capability YAML."""
    with open(path) as f:
        board = yaml.safe_load(f)

    # Schema validation if provided
    if schema:
        try:
            validate(instance=board, schema=schema)
        except ValidationError as e:
            raise ValueError(f"Schema validation failed for {path}: {e.message}")

    return board


def _compute_queue_depth(board: Dict[str, Any]) -> int:
    """Compute inter-core queue depth based on RAM size and strategy."""
    if board.get("isr_serial_strategy") != "multicore":
        return 0
    ram = board.get("ram_size_bytes", 0)
    if ram >= 512000:
        return 32
    elif ram >= 256000:
        return 16
    return 8


def _compute_ringbuf_size(board: Dict[str, Any]) -> int:
    """Compute ISR ring buffer size based on RAM size and strategy."""
    if board.get("isr_serial_strategy") != "uart_rx_isr":
        return 0
    ram = board.get("ram_size_bytes", 0)
    if ram >= 512000:
        return 512
    elif ram >= 192000:
        return 256
    return 128


def generate_platform_caps_h(board: Dict[str, Any]) -> str:
    """Generate platform_caps.h content."""
    lines = [
        "/**",
        " * platform_caps.h",
        " * ----------------",
        f" * Auto-generated platform capabilities for {board['board']} ({board['mcu']})",
        " *",
        " * DO NOT EDIT - Generated by tools/gen_platform_caps.py",
        " */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        f"// Board identification",
        f'#define FERQON_BOARD_NAME          "{board["board"]}"',
        f'#define FERQON_MCU_FAMILY          "{board["mcu"]}"',
        "",
        f"// System capabilities",
        f"#define FERQON_MAX_GPIO            {board['max_gpio']}",
        f"#define FERQON_LED_PIN             {board['led_pin']}",
        f"#define FERQON_PIO_BLOCKS          {board['pio_blocks']}",
        f"#define FERQON_PIO_SM_PER_BLOCK    {board['pio_sm_per_block']}",
        f"#define FERQON_DMA_CHANNELS        {board['dma_channels']}",
        f"#define FERQON_MULTICORE           {1 if board.get('multicore', False) else 0}",
        f"#define FERQON_FLASH_SIZE_BYTES    {board.get('flash_size_bytes', 0)}",
        f"#define FERQON_SYS_CLOCK_HZ        {board.get('sys_clock_hz', 0)}",
        "",
        f"// Scheduling / core topology",
        f"#define FERQON_CORE_COUNT          {board.get('core_count', 1)}",
        f"#define FERQON_RAM_SIZE_BYTES      {board.get('ram_size_bytes', 0)}",
        f"#define FERQON_SCHED_MULTICORE     {1 if board.get('isr_serial_strategy') == 'multicore' else 0}",
        f"#define FERQON_SCHED_UART_ISR      {1 if board.get('isr_serial_strategy') == 'uart_rx_isr' else 0}",
        f"#define FERQON_SCHED_QUEUE_DEPTH   {_compute_queue_depth(board)}",
        f"#define FERQON_ISR_RINGBUF_SIZE    {_compute_ringbuf_size(board)}",
        "",
    ]

    # Network capabilities
    network = board.get("network", {})
    lines.append(f"// Network capabilities")
    lines.append(f"#define FERQON_NET_HAS_WIFI       {1 if 'wifi' in network.get('link', []) else 0}")
    lines.append(f"#define FERQON_NET_HAS_BLE        {1 if 'ble' in network.get('link', []) else 0}")
    lines.append(f"#define FERQON_NET_HAS_ETHERNET  {1 if 'ethernet' in network.get('link', []) else 0}")
    lines.append(f"#define FERQON_NET_HAS_MQTT       {1 if 'mqtt' in network.get('transport', []) else 0}")
    lines.append(f"#define FERQON_NET_HAS_OTA        {1 if network.get('ota', False) else 0}")
    lines.append(f"#define FERQON_PROVISION_SOFTAP   {1 if 'softap' in network.get('provision', []) else 0}")
    lines.append(f"#define FERQON_PROVISION_BLE      {1 if 'ble' in network.get('provision', []) else 0}")
    lines.append("")

    # ADC capabilities
    adc_config = board.get("adc", {})
    lines.append(f"// ADC capabilities")
    lines.append(f"#define FERQON_ADC_RESOLUTION      {adc_config.get('resolution_bits', 12)}")
    lines.append(f"#define FERQON_ADC_VREF_MV         {adc_config.get('vref_mv', 3300)}")
    lines.append("")

    # ADC pin list
    lines.append("// ADC pin list")
    lines.append("static const uint8_t FERQON_ADC_PINS[] = {")
    adc_pins = adc_config.get("pins", [])
    if adc_pins:
        lines.append("    " + ", ".join(str(p) for p in adc_pins))
    else:
        lines.append("    // No ADC pins")
    lines.append("};")
    lines.append(f"#define FERQON_ADC_PIN_COUNT      {len(adc_pins)}")
    lines.append("")

    # PWM pin list
    lines.append("// PWM pin list")
    lines.append("static const uint8_t FERQON_PWM_PINS[] = {")
    pwm_config = board.get("pwm", {})
    pwm_pins = pwm_config.get("pins", [])
    if pwm_pins:
        # Split long lines for readability, add trailing comma to each line
        line_parts = []
        for i, pin in enumerate(pwm_pins):
            if i % 8 == 0:
                line_parts.append("    " + str(pin))
            else:
                line_parts[-1] += f", {pin}"
        # Add trailing comma to each line except the last
        for i in range(len(line_parts) - 1):
            line_parts[i] += ","
        lines.extend(line_parts)
    else:
        lines.append("    // No PWM pins")
    lines.append("};")
    lines.append(f"#define FERQON_PWM_PIN_COUNT      {len(pwm_pins)}")
    lines.append("")

    # Reserved pins
    lines.append("// Reserved pins (not available for general use)")
    lines.append("static const uint8_t FERQON_RESERVED_PINS[] = {")
    reserved_pins = board.get("reserved_pins", [])
    if reserved_pins:
        lines.append("    " + ", ".join(str(p) for p in reserved_pins))
    else:
        lines.append("    // No reserved pins")
    lines.append("};")
    lines.append(f"#define FERQON_RESERVED_PIN_COUNT {len(reserved_pins)}")
    lines.append("")

    # Device descriptor constants
    lines.append("// Device descriptor constants")
    lines.append(f'#define FERQON_DEVICE_TYPE         "{board["device_type"]}"')
    lines.append(f'#define FERQON_PROTOCOL_VERSION    "{board["protocol_version"]}"')
    lines.append(f'#define FERQON_CAPABILITY_VERSION  "{board["capability_version"]}"')
    lines.append(f'#define FERQON_FIRMWARE_VERSION     "{board["firmware_version"]}"')
    lines.append("")

    return "\n".join(lines)


def generate_device_channels_c(board: Dict[str, Any]) -> str:
    """Generate device_channels.c content."""
    lines = [
        "/**",
        " * device_channels.c",
        " * -----------------",
        f" * Auto-generated device channel definitions for {board['board']} ({board['mcu']})",
        " *",
        " * DO NOT EDIT - Generated by tools/gen_platform_caps.py",
        " */",
        "",
        '#include "device_descriptor.h"',
        '#include "platform_caps.h"',
        "",
        "// Device descriptor channel definitions",
        "static const FERQON_IoChannelSpec_t g_device_channels[] = {",
    ]

    # GPIO channels
    max_gpio = board["max_gpio"]
    lines.append("    // GPIO pins")
    lines.append("    {")
    lines.append(f'        .name = "GPIO",')
    lines.append("        .type = FERQON_CHAN_GPIO,")
    lines.append("        .direction = FERQON_DIR_BIDIR,")
    lines.append(f'        .pin_start = 0,')
    lines.append(f'        .pin_count = {max_gpio + 1},')
    lines.append("        .resolution = 1,")
    lines.append("        .value_min = 0,")
    lines.append("        .value_max = 1,")
    lines.append('        .unit = "",')
    lines.append("        .writable = true")
    lines.append("    },")
    lines.append("")

    # ADC channels
    adc_config = board.get("adc", {})
    adc_pins = adc_config.get("pins", [])
    adc_resolution = adc_config.get("resolution_bits", 12)
    if adc_pins:
        lines.append("    // ADC channels")
        for pin in adc_pins:
            lines.append("    {")
            lines.append(f'        .name = "ADC{pin - min(adc_pins)}",')
            lines.append("        .type = FERQON_CHAN_ADC,")
            lines.append("        .direction = FERQON_DIR_INPUT,")
            lines.append(f'        .pin_start = {pin},')
            lines.append("        .pin_count = 1,")
            lines.append(f'        .resolution = {adc_resolution},')
            lines.append("        .value_min = 0,")
            lines.append(f'        .value_max = {(1 << adc_resolution) - 1},')
            lines.append('        .unit = "V",')
            lines.append("        .writable = false")
            lines.append("    },")
        lines.append("")

    # PWM channels
    pwm_config = board.get("pwm", {})
    pwm_pins = pwm_config.get("pins", [])
    if pwm_pins:
        lines.append("    // PWM channels (all PWM-capable pins)")
        lines.append("    {")
        lines.append('        .name = "PWM",')
        lines.append("        .type = FERQON_CHAN_PWM,")
        lines.append("        .direction = FERQON_DIR_OUTPUT,")
        lines.append(f'        .pin_start = 0,')
        lines.append(f'        .pin_count = {max_gpio + 1},')
        lines.append("        .resolution = 16,")  # Common PWM resolution
        lines.append("        .value_min = 0,")
        lines.append("        .value_max = 65535,")
        lines.append('        .unit = "",')
        lines.append("        .writable = true")
        lines.append("    },")
        lines.append("")

    # SPI buses
    for spi in board["spi"]:
        lines.append(f'    // SPI{spi["instance"]}')
        lines.append("    {")
        lines.append(f'        .name = "SPI{spi["instance"]}",')
        lines.append("        .type = FERQON_CHAN_SPI,")
        lines.append("        .direction = FERQON_DIR_BIDIR,")
        lines.append(f'        .pin_start = {spi["sck"][0]},')  # Use first SCK pin as representative
        lines.append("        .pin_count = 4,")  # SCK, MOSI, MISO, CS
        lines.append("        .resolution = 8,")
        lines.append("        .value_min = 0,")
        lines.append("        .value_max = 255,")
        lines.append('        .unit = "",')
        lines.append("        .writable = true")
        lines.append("    },")
        lines.append("")

    # I2C buses
    for i2c in board["i2c"]:
        lines.append(f'    // I2C{i2c["instance"]}')
        lines.append("    {")
        lines.append(f'        .name = "I2C{i2c["instance"]}",')
        lines.append("        .type = FERQON_CHAN_I2C,")
        lines.append("        .direction = FERQON_DIR_BIDIR,")
        lines.append(f'        .pin_start = {i2c["sda"][0]},')  # Use first SDA pin as representative
        lines.append("        .pin_count = 2,")  # SDA, SCL
        lines.append("        .resolution = 8,")
        lines.append("        .value_min = 0,")
        lines.append("        .value_max = 255,")
        lines.append('        .unit = "",')
        lines.append("        .writable = true")
        lines.append("    },")
        lines.append("")

    # UART buses
    for uart in board["uart"]:
        lines.append(f'    // UART{uart["instance"]}')
        lines.append("    {")
        lines.append(f'        .name = "UART{uart["instance"]}",')
        lines.append("        .type = FERQON_CHAN_UART,")
        lines.append("        .direction = FERQON_DIR_BIDIR,")
        lines.append(f'        .pin_start = {uart["tx"][0]},')  # Use first TX pin as representative
        lines.append("        .pin_count = 2,")  # TX, RX
        lines.append("        .resolution = 8,")
        lines.append("        .value_min = 0,")
        lines.append("        .value_max = 255,")
        lines.append('        .unit = "",')
        lines.append("        .writable = true")
        lines.append("    },")
        lines.append("")

    lines.append("};")
    lines.append("")
    lines.append("// Exported function to get device channels")
    lines.append("const FERQON_IoChannelSpec_t* FERQON_Device_GetChannels(size_t* out_count) {")
    lines.append("    if (out_count) {")
    lines.append(f'        *out_count = sizeof(g_device_channels) / sizeof(g_device_channels[0]);')
    lines.append("    }")
    lines.append("    return g_device_channels;")
    lines.append("}")

    return "\n".join(lines)


def generate_pin_macros_h(board: Dict[str, Any]) -> str:
    """Generate pin_macros.h with inline capability check functions."""
    lines = [
        "/**",
        " * pin_macros.h",
        " * ------------",
        f" * Auto-generated pin capability macros for {board['board']} ({board['mcu']})",
        " *",
        " * DO NOT EDIT - Generated by tools/gen_platform_caps.py",
        " */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "// Pin capability validation functions (inline for performance)",
        ""
    ]

    max_gpio = board['max_gpio']
    adc_config = board.get("adc", {})
    pwm_config = board.get("pwm", {})
    reserved_pins = board.get("reserved_pins", [])
    adc_pins = adc_config.get("pins", [])
    pwm_pins = pwm_config.get("pins", [])

    # Pin validation
    lines.append("static inline bool ferqon_cap_pin_is_valid(uint8_t pin) {")
    lines.append(f"    return pin <= {max_gpio};")
    lines.append("}")
    lines.append("")

    # Reserved check
    lines.append("static inline bool ferqon_cap_pin_is_reserved(uint8_t pin) {")
    if reserved_pins:
        lines.append("    switch (pin) {")
        for pin in reserved_pins:
            lines.append(f"        case {pin}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")
    lines.append("")

    # ADC validation
    lines.append("static inline bool ferqon_cap_pin_supports_adc(uint8_t pin) {")
    if adc_pins:
        lines.append("    switch (pin) {")
        for pin in adc_pins:
            lines.append(f"        case {pin}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")
    lines.append("")

    # PWM validation
    lines.append("static inline bool ferqon_cap_pin_supports_pwm(uint8_t pin) {")
    if pwm_pins:
        lines.append("    switch (pin) {")
        for pin in pwm_pins:
            lines.append(f"        case {pin}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")
    lines.append("")

    # Instance validation
    spi = board.get("spi", [])
    i2c = board.get("i2c", [])
    uart = board.get("uart", [])

    lines.append("// Instance validation functions")
    spi_instances = [s["instance"] for s in spi]
    lines.append("static inline bool ferqon_cap_spi_instance_is_valid(uint8_t instance) {")
    if spi_instances:
        lines.append("    switch (instance) {")
        for inst in spi_instances:
            lines.append(f"        case {inst}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")
    lines.append("")

    i2c_instances = [i["instance"] for i in i2c]
    lines.append("static inline bool ferqon_cap_i2c_instance_is_valid(uint8_t instance) {")
    if i2c_instances:
        lines.append("    switch (instance) {")
        for inst in i2c_instances:
            lines.append(f"        case {inst}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")
    lines.append("")

    uart_instances = [u["instance"] for u in uart]
    lines.append("static inline bool ferqon_cap_uart_instance_is_valid(uint8_t instance) {")
    if uart_instances:
        lines.append("    switch (instance) {")
        for inst in uart_instances:
            lines.append(f"        case {inst}:")
        lines.append("            return true;")
        lines.append("        default:")
        lines.append("            return false;")
        lines.append("    }")
    else:
        lines.append("    return false;")
    lines.append("}")

    return "\n".join(lines)


def generate_capabilities_json(board: Dict[str, Any]) -> str:
    """Generate unified capabilities.json for driver matching and validation."""
    capabilities = {
        "device_type": board.get("device_type", board["board"]),
        "mcu": board["mcu"],
        "max_gpio": board["max_gpio"],
        "reserved_pins": board.get("reserved_pins", []),
        "pins": {},
        "peripherals": {}
    }

    # Build pin capability map
    max_gpio = board["max_gpio"]
    for pin in range(max_gpio + 1):
        pin_caps = ["gpio_in", "gpio_out"]

        # Add ADC capability
        adc_config = board.get("adc", {})
        adc_pins = adc_config.get("pins", [])
        if pin in adc_pins:
            pin_caps.append("adc")

        # Add PWM capability
        pwm_config = board.get("pwm", {})
        pwm_pins = pwm_config.get("pins", [])
        if pin in pwm_pins:
            pin_caps.append("pwm")

        # Add SPI capabilities
        for spi in board.get("spi", []):
            instance = spi["instance"]
            if pin in spi["sck"]:
                pin_caps.append(f"spi{instance}_sck")
            if pin in spi["mosi"]:
                pin_caps.append(f"spi{instance}_mosi")
            if pin in spi["miso"]:
                pin_caps.append(f"spi{instance}_miso")
            if pin in spi["cs"]:
                pin_caps.append(f"spi{instance}_cs")

        # Add I2C capabilities
        for i2c in board.get("i2c", []):
            instance = i2c["instance"]
            if pin in i2c["sda"]:
                pin_caps.append(f"i2c{instance}_sda")
            if pin in i2c["scl"]:
                pin_caps.append(f"i2c{instance}_scl")

        # Add UART capabilities
        for uart in board.get("uart", []):
            instance = uart["instance"]
            if pin in uart["tx"]:
                pin_caps.append(f"uart{instance}_tx")
            if pin in uart["rx"]:
                pin_caps.append(f"uart{instance}_rx")

        capabilities["pins"][str(pin)] = pin_caps

    # Build peripheral structure
    for spi in board.get("spi", []):
        instance = spi["instance"]
        capabilities["peripherals"][f"spi{instance}"] = {
            "sck": spi["sck"],
            "mosi": spi["mosi"],
            "miso": spi["miso"],
            "cs": spi["cs"]
        }

    for i2c in board.get("i2c", []):
        instance = i2c["instance"]
        capabilities["peripherals"][f"i2c{instance}"] = {
            "sda": i2c["sda"],
            "scl": i2c["scl"]
        }

    for uart in board.get("uart", []):
        instance = uart["instance"]
        capabilities["peripherals"][f"uart{instance}"] = {
            "tx": uart["tx"],
            "rx": uart["rx"]
        }

    adc_config = board.get("adc", {})
    if adc_config:
        capabilities["peripherals"]["adc"] = {
            "channels": adc_config.get("pins", []),
            "resolution": adc_config.get("resolution_bits", 12),
            "vref_mv": adc_config.get("vref_mv", 3300)
        }

    pwm_config = board.get("pwm", {})
    if pwm_config:
        capabilities["peripherals"]["pwm"] = {
            "slices": board.get("pio_blocks", 0) * board.get("pio_sm_per_block", 4) // 2,  # Approximate
            "pins": pwm_config.get("pins", [])
        }

    return json.dumps(capabilities, indent=2)


def generate_board_json(board: Dict[str, Any]) -> str:
    """Generate JSON mirror of board configuration for backend tooling."""
    return json.dumps(board, indent=2)


def generate_for_board(board_path: Path, output_dir: Path, schema: Dict[str, Any] = None, check_mode: bool = False) -> bool:
    """Generate all files for a single board. Returns True if changes detected (or check_mode fails)."""
    board = load_board_yaml(board_path, schema)
    board_name = board['board']

    if check_mode:
        # In check mode, compare generated content with existing files
        changes = False

        # Check platform_caps.h
        generated_h = generate_platform_caps_h(board)
        existing_h_path = output_dir / "platform_caps.h"
        if existing_h_path.exists():
            if existing_h_path.read_text() != generated_h:
                print(f"CHECK FAIL: {board_name}/platform_caps.h needs regeneration")
                changes = True
        else:
            print(f"CHECK FAIL: {board_name}/platform_caps.h does not exist")
            changes = True

        # Check pin_macros.h
        generated_macros = generate_pin_macros_h(board)
        existing_macros_path = output_dir / "pin_macros.h"
        if existing_macros_path.exists():
            if existing_macros_path.read_text() != generated_macros:
                print(f"CHECK FAIL: {board_name}/pin_macros.h needs regeneration")
                changes = True
        else:
            print(f"CHECK FAIL: {board_name}/pin_macros.h does not exist")
            changes = True

        # Check device_channels.c
        generated_c = generate_device_channels_c(board)
        existing_c_path = output_dir / "device_channels.c"
        if existing_c_path.exists():
            if existing_c_path.read_text() != generated_c:
                print(f"CHECK FAIL: {board_name}/device_channels.c needs regeneration")
                changes = True
        else:
            print(f"CHECK FAIL: {board_name}/device_channels.c does not exist")
            changes = True

        # Check board.json
        generated_json = generate_board_json(board)
        existing_json_path = output_dir / "board.json"
        if existing_json_path.exists():
            if existing_json_path.read_text() != generated_json:
                print(f"CHECK FAIL: {board_name}/board.json needs regeneration")
                changes = True
        else:
            print(f"CHECK FAIL: {board_name}/board.json does not exist")
            changes = True

        # Check capabilities.json
        generated_caps = generate_capabilities_json(board)
        existing_caps_path = output_dir / "capabilities.json"
        if existing_caps_path.exists():
            if existing_caps_path.read_text() != generated_caps:
                print(f"CHECK FAIL: {board_name}/capabilities.json needs regeneration")
                changes = True
        else:
            print(f"CHECK FAIL: {board_name}/capabilities.json does not exist")
            changes = True

        return changes
    else:
        # Generate mode: write files
        output_dir.mkdir(parents=True, exist_ok=True)

        platform_caps_h = generate_platform_caps_h(board)
        (output_dir / "platform_caps.h").write_text(platform_caps_h)

        pin_macros_h = generate_pin_macros_h(board)
        (output_dir / "pin_macros.h").write_text(pin_macros_h)

        device_channels_c = generate_device_channels_c(board)
        (output_dir / "device_channels.c").write_text(device_channels_c)

        board_json = generate_board_json(board)
        (output_dir / "board.json").write_text(board_json)

        capabilities_json = generate_capabilities_json(board)
        (output_dir / "capabilities.json").write_text(capabilities_json)

        print(f"Generated platform capabilities for {board_name}:")
        print(f"  {output_dir / 'platform_caps.h'}")
        print(f"  {output_dir / 'pin_macros.h'}")
        print(f"  {output_dir / 'device_channels.c'}")
        print(f"  {output_dir / 'board.json'}")
        print(f"  {output_dir / 'capabilities.json'}")
        return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate platform capability headers from YAML board definitions")
    parser.add_argument("board", nargs="?", help="Path to board.yml file")
    parser.add_argument("output_dir", nargs="?", help="Output directory for generated files")
    parser.add_argument("--all", action="store_true", help="Generate for all platforms/*/board.yml")
    parser.add_argument("--check", action="store_true", help="Check if generated files are up-to-date (CI mode)")
    args = parser.parse_args()

    # Load schema for validation
    schema = load_board_schema()

    if args.all:
        # Generate for all platforms
        platforms_dir = Path(__file__).parent.parent / "platforms"
        if not platforms_dir.exists():
            sys.exit(f"ERROR: platforms directory not found: {platforms_dir}")

        any_changes = False
        for board_yml in sorted(platforms_dir.glob("*/board.yml")):
            board_name = board_yml.parent.name
            output_dir = board_yml.parent / "generated"
            changes = generate_for_board(board_yml, output_dir, schema, args.check)
            if changes:
                any_changes = True

        if args.check:
            if any_changes:
                print("\nGenerator drift detected! Run: python3 tools/gen_platform_caps.py --all")
                sys.exit(1)
            else:
                print("\nAll generated files are up-to-date.")
                sys.exit(0)

    elif args.board:
        # Generate for single board
        board_path = Path(args.board)
        output_dir = Path(args.output_dir) if args.output_dir else board_path.parent / "generated"

        if not board_path.exists():
            sys.exit(f"ERROR: Board file not found: {board_path}")

        changes = generate_for_board(board_path, output_dir, schema, args.check)

        if args.check:
            if changes:
                print("\nGenerator drift detected!")
                sys.exit(1)
            else:
                print("\nGenerated files are up-to-date.")
                sys.exit(0)

    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
