#!/usr/bin/env python3
"""
pio_pre_build.py
----------------
PlatformIO pre-build hook that generates platform capability headers
and device channel definitions from board YAML files.

This script is called by PlatformIO before each build via:
    extra_scripts = pre:tools/pio_pre_build.py

Usage:
    Automatically invoked by PlatformIO during build process.

Environment variables from PlatformIO:
    - PROJECT_DIR: Project root directory
    - PLATFORMIO_ENV_NAME: Current environment name (e.g., pico_arduino, esp32)
"""

import os
import sys
import json
import yaml
import subprocess
import time
from pathlib import Path


def get_firmware_dir() -> Path:
    """Get the firmware directory from environment or default."""
    project_dir = os.environ.get("PROJECT_DIR", ".")
    return Path(project_dir)


def generate_build_timestamp(firmware_dir: Path) -> bool:
    """Generate a header file with the build timestamp."""
    generated_dir = firmware_dir / "generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp_file = generated_dir / "build_timestamp.h"
    build_time = int(time.time())
    
    content = f"""// Auto-generated by pio_pre_build.py
// Build timestamp (Unix epoch)
#ifndef BUILD_TIMESTAMP_H
#define BUILD_TIMESTAMP_H

#define FERQON_BUILD_TIMESTAMP {build_time}U

#endif // BUILD_TIMESTAMP_H
"""
    
    with open(timestamp_file, 'w') as f:
        f.write(content)
    
    print(f"Generated build timestamp: {build_time} ({time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(build_time))} UTC)")
    return True


def get_board_for_env(env_name: str) -> str:
    """Map PlatformIO environment name to board JSON file."""
    env_map = {
        "pico_arduino": "pico",
        "pico_native":  "pico",
        "rp2040":       "rp2040",
        "esp32":        "esp32",
        "esp32s3":      "esp32s3",
        "stm32f4":      "stm32f4",
        "stm32f7":      "stm32f7",
        "teensy40":     "teensy40",
        "teensy41":     "teensy41",
    }
    return env_map.get(env_name, env_name)


def load_board_yaml(platforms_dir: Path, board_name: str) -> dict:
    """Load board YAML file and extract pio_env mapping."""
    board_path = platforms_dir / board_name / "board.yml"
    if not board_path.exists():
        print(f"Warning: Board YAML not found: {board_path}")
        return None

    with open(board_path) as f:
        return yaml.safe_load(f)


def print_board_summary(board_data: dict) -> None:
    """Print a human-readable board capability summary to the build log."""
    strategy = board_data.get("isr_serial_strategy", "unknown")
    core_count = board_data.get("core_count", 1)
    ram_kb = board_data.get("ram_size_bytes", 0) // 1024
    flash_kb = board_data.get("flash_size_bytes", 0) // 1024
    clock_mhz = board_data.get("sys_clock_hz", 0) // 1_000_000
    
    # Get ADC pins from new YAML structure
    adc_config = board_data.get("adc", {})
    adc_pins = adc_config.get("pins", [])

    if strategy == "multicore":
        sched_desc = f"multicore (Core 0=serial RX, Core 1=command exec)"
    elif strategy == "uart_rx_isr":
        sched_desc = f"single-core (UART RX ISR + ring buffer → main loop)"
    else:
        sched_desc = strategy

    print("┌─ Board Summary " + "─" * 44)
    print(f"│  Board:     {board_data.get('board', '?')} ({board_data.get('device_type', '?')})")
    print(f"│  MCU:       {board_data.get('mcu', '?')}")
    print(f"│  Cores:     {core_count}")
    print(f"│  Strategy:  {sched_desc}")
    print(f"│  RAM:       {ram_kb} KB")
    print(f"│  Flash:     {flash_kb} KB")
    print(f"│  Clock:     {clock_mhz} MHz")
    print(f"│  GPIO:      0–{board_data.get('max_gpio', '?')}")
    print(f"│  ADC pins:  {len(adc_pins)}")
    print(f"│  Backend:   {board_data.get('backend', '?')}")
    print("└" + "─" * 60)


def run_gen_platform_caps(firmware_dir: Path, board_data: dict) -> bool:
    """Run the platform capability generator."""
    board_name = board_data.get("board", "unknown")
    platforms_dir = firmware_dir / "platforms"
    generated_dir = platforms_dir / board_name / "generated"
    gen_script = firmware_dir / "tools" / "gen_platform_caps.py"

    # Ensure generated directory exists
    generated_dir.mkdir(parents=True, exist_ok=True)

    board_yml = platforms_dir / board_name / "board.yml"

    if not gen_script.exists():
        print(f"Error: Generator script not found: {gen_script}")
        return False

    cmd = [
        sys.executable,
        str(gen_script),
        str(board_yml),
        str(generated_dir)
    ]

    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"Error generating platform caps: {result.stderr}")
        return False

    print(f"Generated platform capabilities for {board_name}")
    return True


def main():
    """Main entry point for PlatformIO pre-build hook."""
    print("=" * 60)
    print("Ferqon PlatformIO Pre-Build Hook")
    print("=" * 60)

    # Get environment from PlatformIO
    env_name = os.environ.get("PLATFORMIO_ENV_NAME", "pico_arduino")
    print(f"Environment: {env_name}")

    # Get firmware directory
    firmware_dir = get_firmware_dir()
    print(f"Firmware directory: {firmware_dir}")

    # Generate build timestamp
    generate_build_timestamp(firmware_dir)

    # Map env to board
    board_name = get_board_for_env(env_name)
    print(f"Board: {board_name}")

    # Load board YAML
    platforms_dir = firmware_dir / "platforms"
    board_data = load_board_yaml(platforms_dir, board_name)

    if not board_data:
        print(f"Warning: Could not load board data for {board_name}")
        # Continue build anyway - may fail later if headers missing
        return 0

    # Print board summary so every build log shows core topology clearly
    print_board_summary(board_data)

    # Check pio_env matches
    expected_pio_env = board_data.get("pio_env", board_name)
    if expected_pio_env != env_name:
        print(f"Warning: Environment mismatch. Board expects '{expected_pio_env}', got '{env_name}'")

    # Generate platform capabilities
    if not run_gen_platform_caps(firmware_dir, board_data):
        print("Warning: Platform capability generation failed")
        # Don't fail the build - let PlatformIO continue and report errors

    # Check for commands.json and generate commands.hpp if needed
    commands_json_paths = [
        firmware_dir / ".." / "commands.json",  # repo root
        firmware_dir / ".." / "open_sdk" / "sdk" / "serial" / "commands.json",
        firmware_dir / ".." / "commands" / "commands.json",
    ]

    # Pinmap paths for commands generation
    pinmap_json_paths = [
        firmware_dir / ".." / "protocol_sdk" / "sdk" / "serial" / "driver" / "pico_pinmap.json",
        firmware_dir / ".." / "commands" / "pico_pinmap.json",
    ]

    gen_commands_script = firmware_dir / "tools" / "gen_commands.py"
    if gen_commands_script.exists():
        for commands_json in commands_json_paths:
            if commands_json.exists():
                generated_dir = firmware_dir / "generated"
                cmd = [
                    sys.executable,
                    str(gen_commands_script),
                    str(commands_json),
                    str(generated_dir / "commands.hpp")
                ]

                # Add pinmap if available
                for pinmap_json in pinmap_json_paths:
                    if pinmap_json.exists():
                        cmd.append(str(pinmap_json))
                        print(f"Using pinmap: {pinmap_json}")
                        break

                print(f"Running: {' '.join(cmd)}")
                result = subprocess.run(cmd, capture_output=True, text=True)
                if result.returncode == 0:
                    print("Generated commands.hpp")
                else:
                    print(f"Warning: commands.hpp generation failed: {result.stderr}")
                break

    print("=" * 60)
    print("Pre-build hook complete")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    sys.exit(main())
